live inside the zpool

diff --git a/generate b/generate
--- a/generate
+++ b/generate
@@ -1,20 +1,30 @@
 #!/bin/bash -e
 # set things up
-mount="$(dirname "$(readlink -f "$0")")"
-cd "$mount"
+find_dataset() {
+  mount -t zfs | awk 'BEGIN { ret = 1; } $3 == mountpoint { print $1; ret = 0; exit; } END { exit ret; }' mountpoint="$1"
+}
+
+dir="$(dirname "$(readlink -f "$0")")"
+dataset="$(find_dataset "$dir")" || { echo "could not find bootr\'s own dataset. are you sure it's at the root of a filesystem in your pool?"; exit 1; }
+pool="$(cut -d/ -f1 <<< "$dataset")"
+dataset_name="$(cut -d/ -f2- <<< "$dataset")"
+
+efi="/boot/efi"
+if ! mountpoint -q "$efi"; then
+  echo "error: $efi is not a mountpoint" >&2
+  exit 1
+fi
 
 echo "reading boot.cfg" >&2
 
-[ -f "${mount}/boot.cfg" ] && source loadconfig || fresh=true
+[ -f "${dir}/boot.cfg" ] && source loadconfig || fresh=true
 
-[ -z "${root_uuid}" ] && root_uuid="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
-[ -z "${root_pool}" ] && root_pool="storage"
+[ -z "${uuid}" ] && uuid="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
 
 # regenerate boot.cfg
 cat > boot.cfg <<EOF
 # vim: ft=grub
-set root_uuid="${root_uuid}"
-set root_pool="${root_pool}"
+set uuid="${uuid}"
 EOF
 
 echo "built boot.cfg" >&2
@@ -31,14 +41,7 @@ echo>&2
 
 echo "creating in-pool GRUB config" >&2
 
-if zfs list "${root_pool}/grub" >/dev/null 2>&1; then
-  echo "found GRUB filesystem" >&2
-else
-  zfs create "${root_pool}/grub"
-  echo "created GRUB filesystem" >&2
-fi
-
-zfs list -Ho name,eu.nathan7:boot -r "${root_pool}" | awk -F '\t' 'tolower($2) == "true" {print $1}' | cut -d/ -f2- | while read dataset; do
+zfs list -Ho name,eu.nathan7:boot -r "${pool}" | awk -F '\t' 'tolower($2) == "true" {print $1}' | cut -d/ -f2- | while read dataset; do
   echo "adding boot entry $dataset" >&2
   cat <<EOF
 menuentry "$dataset" {
@@ -48,7 +51,7 @@ menuentry "$dataset" {
   source \${boot_path}/grub.cfg
 }
 EOF
-done > "/${root_pool}/grub/grub.cfg"
+done > grub.cfg
 echo "built in-pool GRUB config" >&2
 
 echo >&2
@@ -56,12 +59,15 @@ echo >&2
 # set ourselves up in a temporary dir and start building our GRUB image
 echo "building EFI GRUB image" >&2
 
-dir="$(mktemp -d)"
-cd "$dir"
+tmp="$(mktemp -d)"
+cd "$tmp"
 mkdir -p boot/grub
 
-cat "$mount/boot.cfg" - >> boot/grub/grub.cfg <<EOF
-set root_uuid_raw="$(sed "s/-//g" <<< "$root_uuid")"
+cat >> boot/grub/grub.cfg <<EOF
+# vim: ft=grub
+set root_pool="${pool}"
+set root_uuid="${uuid}"
+set root_uuid_raw="$(sed "s/-//g" <<< "${uuid}")"
 set timeout=0
 
 if keystatus --shift; then
@@ -80,7 +86,7 @@ if keystatus --shift; then
 fi
 
 search --no-floppy --label --set \${root_pool}
-source /grub/@/grub.cfg
+source /${dataset_name}/@/grub.cfg
 EOF
 
 if command -v grub-mkstandalone > /dev/null; then
@@ -92,9 +98,9 @@ else
   exit 255
 fi
 
-mkdir -p "$mount/EFI/BOOT"
-${grub_mkstandalone} -O x86_64-efi --modules='gfxterm gfxmenu efi_gop efi_uga font part_gpt part_msdos luks zfs' --locales='en@quot' --themes='' -o "$mount/EFI/BOOT/bootx64.efi" boot/grub/grub.cfg
+mkdir -p "$efi/EFI/BOOT"
+${grub_mkstandalone} -O x86_64-efi --modules='gfxterm gfxmenu efi_gop efi_uga font part_gpt part_msdos luks zfs' --locales='en@quot' --themes='' -o "$efi/EFI/BOOT/bootx64.efi" boot/grub/grub.cfg
 
-rm -rf "$dir"
+rm -rf "$tmp"
 
 echo "done" >&2
