preliminary BIOS support

diff --git a/generate-image b/generate-image
--- a/generate-image
+++ b/generate-image
@@ -18,7 +18,6 @@ else
 fi
 
 # set ourselves up in a temporary dir and start building our GRUB image
-echo "building EFI GRUB image" >&2
 
 tmp="$(mktemp -d)"
 trap "{ rm -rf $tmp; }" EXIT
@@ -52,8 +51,13 @@ fi
 search --no-floppy --label --set \${root_pool}
 source /${dataset_name}/@/grub.cfg
 EOF
+modules='gfxterm gfxmenu font part_gpt part_msdos luks zfs'
+efi_modules="efi_gop efi_uga $modules"
+bios_modules="vbe $modules"
 
-(cd "$tmp" && ${grub_mkstandalone} -O x86_64-efi --modules='gfxterm gfxmenu efi_gop efi_uga font part_gpt part_msdos luks zfs' --locales='en@quot' --themes='' -o bootx64.efi boot/grub/grub.cfg)
+echo "building EFI GRUB image" >&2
+
+(cd "$tmp" && ${grub_mkstandalone} -O x86_64-efi --modules="$efi_modules" --locales='en@quot' --themes='' -o bootx64.efi boot/grub/grub.cfg)
 
 if [ -n "$sign" ]; then
   sbsign --key "${sign}.key" --cert "${sign}.crt" --output "$tmp/bootx64.efi.signed" "$tmp/bootx64.efi"
@@ -64,3 +68,10 @@ mkdir -p "$efi/EFI/BOOT"
 mv "$tmp/bootx64.efi" "$efi/EFI/BOOT/bootx64.efi"
 
 echo "built EFI GRUB image" >&2
+
+if [ "$bios" = y ] || [ "$bios" = yes ] || [ "$bios" = true ] || [ "$bios" = 1 ]; then
+  echo "building BIOS GRUB" >&2
+  efi_dev="$(mount | awk 'BEGIN { ret = 1; } $3 == mountpoint { print $1; ret = 0; exit; } END { exit ret; }' mountpoint="$efi")" || { echo "could not find boot partition" >&2; exit 1; }
+  grub-install --target i386-pc --install-modules="$bios_modules" --modules "$bios_modules" --boot-directory "$efi" "$efi_dev"
+  echo "built BIOS GRUB" >&2
+fi
